name: jawla_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  pin_code_fields: ^7.4.0
  blurrycontainer: 1.0.2
  like_button: ^2.0.5
  horizontal_center_date_picker: ^2.1.1
  flutter_rounded_date_picker: ^3.0.4
  flutter_time_picker_spinner: ^2.0.0
  numberpicker: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: fonts/Poppins/Poppins-Light.ttf
  #       - asset: fonts/Poppins/Poppins-Regular.ttf
  #       - asset: fonts/Poppins/Poppins-Medium.ttf
  #       - asset: fonts/Poppins/Poppins-SemiBold.ttf
  #       - asset: fonts/Poppins/Poppins-Bold.ttf
